<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Order;
use App\Models\Plan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

class DemoUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');

        // Idempotency check: if the demo user already exists, assume this seeder was already run
        if (User::where('email', 'premium.demo@aruna.id')->exists() && User::count() >= 700) {
            $this->command->info('DemoUsersSeeder has already been run. Skipping.');
            return;
        }

        // Create a dummy plan if none exists for the orders
        $plan = Plan::firstOrCreate(
            ['id' => 'premium-monthly'],
            [
                'name' => 'Premium Monthly',
                'price' => 150000,
                'billing_cycle' => 'monthly',
                'features' => ['All features'],
                'is_active' => true,
            ]
        );

        // Ensure we have exactly 700 users generated by this seeder
        // We will create 152 paid orders of Rp 150,000 to get a total of 22,800,000.
        // 22,800,000 / 700 = ~Rp 32,571 ARPU
        $totalUsersToGenerate = 700;
        $usersWithPaidOrders = 152;
        
        $password = Hash::make('password');

        // 1. Create the specific Demo Premium User
        $demoUser = User::firstOrCreate(
            ['email' => 'premium.demo@aruna.id'],
            [
                'name' => 'Premium Demo Parent',
                'password' => $password,
                'role' => 'parent',
                'subscription_status' => 'premium',
                'email_verified_at' => now(),
            ]
        );

        // Create a paid order for the demo user
        Order::create([
            'id' => Str::uuid(),
            'user_id' => $demoUser->id,
            'plan_id' => $plan->id,
            'subtotal' => 150000,
            'total_amount' => 150000,
            'status' => 'paid',
            'paid_at' => now(),
        ]);

        $usersGenerated = 1; // We just created 1
        $paidOrdersCreated = 1;

        // 2. Generate the rest of the 699 users
        $usersToInsert = [];
        for ($i = 0; $i < $totalUsersToGenerate - 1; $i++) {
            $isPremium = $paidOrdersCreated < $usersWithPaidOrders;
            
            $usersToInsert[] = [
                'name' => $faker->name,
                'email' => $faker->unique()->safeEmail,
                'email_verified_at' => now(),
                'password' => $password,
                'role' => 'parent',
                'subscription_status' => $isPremium ? 'premium' : 'free',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ];

            $paidOrdersCreated += $isPremium ? 1 : 0;
        }

        // Insert in chunks to avoid memory issues
        foreach (array_chunk($usersToInsert, 100) as $chunk) {
            User::insert($chunk);
        }

        // We need to fetch the inserted premium users to create orders for them
        // because we used `insert` which doesn't return models.
        // We can just fetch the recently created users where subscription is premium and they don't have orders yet.
        $recentPremiumUsers = User::where('subscription_status', 'premium')
            ->where('email', '!=', 'premium.demo@aruna.id')
            ->whereDoesntHave('orders')
            ->limit($usersWithPaidOrders - 1)
            ->get();

        $ordersToInsert = [];
        foreach ($recentPremiumUsers as $user) {
            $ordersToInsert[] = [
                'id' => Str::uuid(),
                'user_id' => $user->id,
                'plan_id' => $plan->id,
                'subtotal' => 150000,
                'total_amount' => 150000,
                'status' => 'paid',
                'paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        foreach (array_chunk($ordersToInsert, 100) as $chunk) {
            Order::insert($chunk);
        }
    }
}
