<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Order;
use App\Models\Plan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DemoUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Idempotency check: if the demo user already exists, assume this seeder was already run
        if (User::where('email', 'premium.demo@aruna.id')->exists() && User::count() >= 700) {
            $this->command?->info('DemoUsersSeeder has already been run. Skipping.');
            return;
        }

        // Setup faker with fallback for production environments where fakerphp/faker may not be installed
        $faker = null;
        if (class_exists(\Faker\Factory::class)) {
            $faker = \Faker\Factory::create('id_ID');
        }

        $indonesianFirstNames = [
            'Ahmad', 'Budi', 'Citra', 'Dewi', 'Eko', 'Fajar', 'Gita', 'Hadi', 'Indah', 'Joko',
            'Kartika', 'Lestari', 'Muhammad', 'Nur', 'Oki', 'Putri', 'Rahmat', 'Siti', 'Tri', 'Utami',
            'Wahyu', 'Yusuf', 'Zul', 'Rian', 'Bayu', 'Dian', 'Fitri', 'Hendra', 'Intan', 'Mega',
            'Nanda', 'Pratama', 'Rini', 'Surya', 'Taufik', 'Vina', 'Wulan', 'Agus', 'Anisa', 'Bambang',
            'Chandra', 'Desi', 'Edi', 'Farah', 'Gilang', 'Hesti', 'Imam', 'Jihan', 'Kurniawan', 'Maya',
            'Rizky', 'Aditya', 'Ayu', 'Bagus', 'Dwi', 'Endah', 'Firman', 'Gunawan', 'Hasan', 'Ilham'
        ];

        $indonesianLastNames = [
            'Pratama', 'Saputra', 'Wijaya', 'Kusuma', 'Hidayat', 'Santoso', 'Setiawan', 'Nugroho', 'Lestari', 'Wulandari',
            'Permana', 'Gunawan', 'Siregar', 'Nasution', 'Batubara', 'Pangestu', 'Suharto', 'Yuliana', 'Anggraini', 'Mahendra',
            'Kurniawan', 'Ramadhan', 'Utomo', 'Wicaksono', 'Subagyo', 'Purwanto', 'Susanto', 'Hartono', 'Sari', 'Handayani',
            'Firmansyah', 'Budiman', 'Wibowo', 'Cahyono', 'Irawan', 'Prasetyo', 'Hermawan', 'Mulyadi', 'Simanjuntak', 'Siregar'
        ];

        $domains = ['gmail.com', 'yahoo.com', 'outlook.com', 'mail.com', 'aruna.id'];

        // Create a dummy plan if none exists for the orders
        $plan = Plan::firstOrCreate(
            ['id' => 'premium_monthly'],
            [
                'name' => 'Paket Premium (Bulanan)',
                'price' => 50000.00,
                'billing_cycle' => 'monthly',
                'features' => ['Semua Modul Edukasi', 'Simulasi AR Immersive'],
                'is_active' => true,
            ]
        );

        // Ensure we have exactly 700 users generated by this seeder
        // We will create 152 paid orders of Rp 150,000 to get a total of 22,800,000.
        // 22,800,000 / 700 = ~Rp 32,571 ARPU
        $totalUsersToGenerate = 700;
        $usersWithPaidOrders = 152;
        
        $password = Hash::make('password');

        // 1. Create the specific Demo Premium User
        $demoUser = User::firstOrCreate(
            ['email' => 'premium.demo@aruna.id'],
            [
                'name' => 'Premium Demo Parent',
                'password' => $password,
                'role' => 'parent',
                'subscription_status' => 'premium',
                'email_verified_at' => now(),
            ]
        );

        // Create a paid order for the demo user if not already present
        if (!Order::where('user_id', $demoUser->id)->exists()) {
            Order::create([
                'id' => Str::uuid(),
                'user_id' => $demoUser->id,
                'plan_id' => $plan->id,
                'subtotal' => 150000,
                'total_amount' => 150000,
                'payment_method' => 'bank_transfer',
                'payment_proof_path' => 'payment_proofs/demo-proof.jpg',
                'status' => 'paid',
                'paid_at' => now(),
            ]);
        }

        $paidOrdersCreated = 1;

        // 2. Generate the rest of the 699 users
        $usersToInsert = [];
        for ($i = 0; $i < $totalUsersToGenerate - 1; $i++) {
            $isPremium = $paidOrdersCreated < $usersWithPaidOrders;

            if ($faker) {
                $name = $faker->name();
                $email = $faker->unique()->safeEmail();
            } else {
                $first = $indonesianFirstNames[array_rand($indonesianFirstNames)];
                $last = $indonesianLastNames[array_rand($indonesianLastNames)];
                $name = $first . ' ' . $last;
                $email = Str::slug($first) . '.' . Str::slug($last) . '.' . Str::random(5) . '@' . $domains[array_rand($domains)];
            }
            
            $usersToInsert[] = [
                'name' => $name,
                'email' => $email,
                'email_verified_at' => now(),
                'password' => $password,
                'role' => 'parent',
                'subscription_status' => $isPremium ? 'premium' : 'free',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ];

            $paidOrdersCreated += $isPremium ? 1 : 0;
        }

        // Insert in chunks to avoid memory issues
        foreach (array_chunk($usersToInsert, 100) as $chunk) {
            User::insert($chunk);
        }

        // Create orders for recently inserted premium users
        $recentPremiumUsers = User::where('subscription_status', 'premium')
            ->where('email', '!=', 'premium.demo@aruna.id')
            ->whereDoesntHave('orders')
            ->limit($usersWithPaidOrders - 1)
            ->get();

        $ordersToInsert = [];
        foreach ($recentPremiumUsers as $user) {
            $ordersToInsert[] = [
                'id' => (string) Str::uuid(),
                'user_id' => $user->id,
                'plan_id' => $plan->id,
                'subtotal' => 150000,
                'total_amount' => 150000,
                'payment_method' => 'bank_transfer',
                'payment_proof_path' => 'payment_proofs/demo-proof.jpg',
                'status' => 'paid',
                'paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        foreach (array_chunk($ordersToInsert, 100) as $chunk) {
            Order::insert($chunk);
        }

        // Create 3 demo pending approval orders for testing/demoing admin verification
        $freeUsersForPending = User::where('subscription_status', 'free')
            ->whereDoesntHave('orders')
            ->limit(3)
            ->get();

        foreach ($freeUsersForPending as $idx => $user) {
            Order::create([
                'id' => (string) Str::uuid(),
                'user_id' => $user->id,
                'plan_id' => $plan->id,
                'subtotal' => 50000,
                'tax_amount' => 5500,
                'unique_code' => 123 + $idx,
                'total_amount' => 55623 + $idx,
                'payment_method' => 'bank_transfer',
                'payment_proof_path' => 'payment_proofs/demo-proof.jpg',
                'status' => 'pending_approval',
                'created_at' => now()->subMinutes(15 * ($idx + 1)),
                'updated_at' => now()->subMinutes(15 * ($idx + 1)),
            ]);
        }

        $this->command?->info('DemoUsersSeeder completed successfully.');
    }
}
